backend:
  name: git-gateway
  branch: master # ¡Importante! Cambiado de main a master
  commit_messages:
    create: "Añadido nuevo Valiente: {{slug}}"
    update: "Actualizada ficha de {{slug}}"
    delete: "Eliminado {{slug}}"

publish_mode: simple
display_url: https://sospatitasilicitanas.netlify.app
local_backend: false

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "animales"
    label: "Gestionar Valientes"
    label_singular: "Valiente"
    folder: "content/animales"
    create: true
    format: "frontmatter" # Asegura que el formato sea limpio
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
      - {label: "Especie", name: "species", widget: "select", options: ["Perro", "Gato", "Otro"]}
      - {label: "Edad", name: "age", widget: "string"}
      - {label: "Tamaño", name: "size", widget: "select", options: ["Pequeño", "Mediano", "Grande"]}
      - {label: "Estado", name: "status", widget: "select", options: ["Disponible", "Urgente", "Reservado", "Adoptado"]}
      - {label: "Descripción", name: "body", widget: "markdown", minimal: true}